basePath: /
definitions:
  http.InviteDebugResponse:
    description: Parsed SIP request and response with raw packets
    properties:
      data:
        properties:
          invite:
            items:
              $ref: '#/definitions/http.SIPHeader'
            type: array
          result:
            items:
              $ref: '#/definitions/http.SIPHeader'
            type: array
        type: object
    type: object
  http.SIPHeader:
    description: SIP Header pair
    properties:
      name:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
  description: SIP Simulation and Policy Engine for internal debugging.
  title: goMobile
  version: 25.11.24
paths:
  /simulation:
    get:
      consumes:
      - application/json
      description: Выполняет симуляцию SIP INVITE, прогоняет его через бизнес-логику
        Policy (logic) и возвращает INVITE/RESPONSE в сыром и разобранном виде.
      parameters:
      - description: A-number (From)
        in: query
        name: a_number
        required: true
        type: string
      - description: B-number (To)
        in: query
        name: b_number
        required: true
        type: string
      - description: C-number (Diversion)
        in: query
        name: c_number
        type: string
      - description: Источник SIP пакета (X-SrcIP)
        in: query
        name: src_ip
        required: true
        type: string
      - description: IP SBC (по умолчанию 0.0.0.0)
        in: query
        name: sbc_ip
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Успешная симуляция
          schema:
            $ref: '#/definitions/http.InviteDebugResponse'
        "500":
          description: Ошибка обработки URI или другого системного компонента
          schema:
            additionalProperties:
              type: string
            type: object
      summary: SIP Policy Simulation
      tags:
      - Simulation
swagger: "2.0"
